In [151]:
import pandas as pd
from datetime import datetime
import re



pd.set_option('display.max_columns', None)

In [198]:
df = pd.read_csv('dim_date_times.csv')
df

,Unnamed: 0,timestamp,month,year,day,time_period,date_uuid
0,0,22:00:06,9,2012,19,Evening,3b7ca996-37f9-433f-b6d0-ce8391b615ad
1,1,22:44:06,2,1997,10,Evening,adc86836-6c35-49ca-bb0d-65b6507a00fa
2,2,10:05:37,4,1994,15,Morning,5ff791bf-d8e0-4f86-8ceb-c7b60bef9b31
3,3,17:29:27,11,2001,6,Midday,1b01fcef-5ab9-404c-b0d4-1e75a0bd19d8
4,4,22:40:33,12,2015,31,Evening,dfa907c1-f6c5-40f0-aa0d-40ed77ac5a44
...,...,...,...,...,...,...,...
120156,120156,22:56:56,11,2022,12,Evening,d6c4fb31-720d-4e94-aa6b-dcbcb85f2bb7
120157,120157,18:25:20,5,1997,31,Evening,f7722027-1aae-49c3-8f8d-853e93f9f3e6
120158,120158,18:21:40,9,2011,13,Evening,4a3b9851-52e1-463c-ac81-1960f141444e
120159,120159,19:10:53,7,2013,12,Evening,64974909-0d4b-42a2-822a-73b5695e8bfb
120160,120160,21:17:12,3,2008,18,Evening,55c228c7-14ee-4d46-99a9-01dfc57d1adf

In [200]:
def clean_date_time(df):
        df['month']         =  pd.to_numeric( df['month'],errors='coerce', downcast="integer")
        df['year']          =  pd.to_numeric( df['year'], errors='coerce', downcast="integer")
        df['day']           =  pd.to_numeric( df['day'], errors='coerce', downcast="integer")
        df['timestamp']     =  pd.to_datetime(df['timestamp'], format='%H:%M:%S', errors='coerce')
        df.dropna(how='any',inplace= True)
#         del df['index']
        df.drop(columns='Unnamed: 0',inplace=True)
        df.reset_index(drop=True)       
        print(df.head())
clean_date_time(df)

            timestamp  month  year  day time_period  \
0 1900-01-01 22:00:06      9  2012   19     Evening
1 1900-01-01 22:44:06      2  1997   10     Evening
2 1900-01-01 10:05:37      4  1994   15     Morning
3 1900-01-01 17:29:27     11  2001    6      Midday
4 1900-01-01 22:40:33     12  2015   31     Evening

                              date_uuid
0  3b7ca996-37f9-433f-b6d0-ce8391b615ad
1  adc86836-6c35-49ca-bb0d-65b6507a00fa
2  5ff791bf-d8e0-4f86-8ceb-c7b60bef9b31
3  1b01fcef-5ab9-404c-b0d4-1e75a0bd19d8
4  dfa907c1-f6c5-40f0-aa0d-40ed77ac5a44

In [177]:

# df.drop(columns='1',inplace=True)
# df.drop(columns='Unnamed: 0',inplace=True)
# df.drop(columns='first_name',inplace=True)
# df.drop(columns='last_name',inplace=True)
# del df['index']
df.reset_index(drop=True)
# df.reset_index(drop=True, inplace=True)
# df.drop(columns='level_0',inplace=True)
# df.dropna(how='any')
df
# df.drop(columns='level_0', inplace = True)
# df.loc[df['unit'] == 'x', 'weight']

,timestamp,month,year,day,time_period,date_uuid
0,22:00:06,9,2012,19,Evening,3b7ca996-37f9-433f-b6d0-ce8391b615ad
1,22:44:06,2,1997,10,Evening,adc86836-6c35-49ca-bb0d-65b6507a00fa
2,10:05:37,4,1994,15,Morning,5ff791bf-d8e0-4f86-8ceb-c7b60bef9b31
3,17:29:27,11,2001,6,Midday,1b01fcef-5ab9-404c-b0d4-1e75a0bd19d8
4,22:40:33,12,2015,31,Evening,dfa907c1-f6c5-40f0-aa0d-40ed77ac5a44
...,...,...,...,...,...,...
120156,22:56:56,11,2022,12,Evening,d6c4fb31-720d-4e94-aa6b-dcbcb85f2bb7
120157,18:25:20,5,1997,31,Evening,f7722027-1aae-49c3-8f8d-853e93f9f3e6
120158,18:21:40,9,2011,13,Evening,4a3b9851-52e1-463c-ac81-1960f141444e
120159,19:10:53,7,2013,12,Evening,64974909-0d4b-42a2-822a-73b5695e8bfb
120160,21:17:12,3,2008,18,Evening,55c228c7-14ee-4d46-99a9-01dfc57d1adf

In [191]:
df.isna().sum()

index          0
timestamp      0
month          0
year           0
day            0
time_period    0
date_uuid      0
dtype: int64

In [187]:
# rows_with_nan = df[df.isna().any(axis=1)]
# rows_with_nan
df.dropna(how='all', inplace = True)

In [122]:
df.drop(columns='new', inplace = True)

In [196]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 120123 entries, 0 to 120122
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Unnamed: 0   120123 non-null  int64
 1   timestamp    120123 non-null  datetime64[ns]
 2   month        120123 non-null  int8
 3   year         120123 non-null  int16
 4   day          120123 non-null  int8
 5   time_period  120123 non-null  object
 6   date_uuid    120123 non-null  object
dtypes: datetime64[ns](1), int16(1), int64(1), int8(2), object(2)
memory usage: 5.0+ MB

In [173]:
df['product_quantity'].sum()

481786

In [165]:
def isDigits(self,num):
        return str(num) if str(num).isdigit() else np.nan
    
df['card_number'] = df.loc[df['card_number']].apply(lambda x: isDigits(x))

In [171]:
df.dtypes
# df

date_uuid           object
user_uuid           object
card_number          int64
store_code          object
product_code        object
product_quantity     int64
dtype: object

In [149]:
def clean_products_data(self, df):
    df =  self.clean_invalid_date(df,'date_added')
    df['product_price (Â£)'] = df['product_price'].str.replace('Â£', '').astype(float)
    df.dropna(how='any',inplace= True)
    df.reset_index(inplace=True)       
    return df
# clean_products_data(df)
#

,index,product_name,product_price,weight,category,EAN,date_added,uuid,removed,product_code,unit,product_price (Â£)
0,0,FurReal Dazzlin' Dimples My Playful Dolphin,Â£39.99,1.6kg,toys-and-games,7425710935115,2005-12-02,83dc0a69-f96f-4c34-bcb7-928acae19a94,Still_avaliable,R7-3126933h,kg,39.99
1,1,Tiffany's World Day Out At The Park,Â£12.99,0.48kg,toys-and-games,487128731892,2006-01-09,712254d7-aea7-4310-aff8-8bcdd0aec7ff,Still_avaliable,C2-7287916l,kg,12.99
2,2,Tiffany's World Pups Picnic Playset,Â£7.00,590g,toys-and-games,1945816904649,1997-03-29,b089ef6f-b628-4e37-811d-fffe0102ba64,Still_avaliable,S7-1175877v,g,7.00
3,3,Tiffany's World Wildlife Park Adventures,Â£12.99,540g,toys-and-games,1569790890899,2013-03-20,d55de422-8b98-47d6-9991-e4bc4c5c0cb0,Removed,D8-8421505n,g,12.99
4,4,Cosatto Cosy Dolls Pram,Â£30.00,1.91kg,toys-and-games,7142740213920,2007-12-23,7945b657-cb02-4cc5-96cf-f65ed0a8f235,Still_avaliable,B6-2596063a,kg,30.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1841,1848,Goodmans Qi Autosense In Car Phone Holder,Â£15.00,125g,diy,8185827751600,2020-08-28,3ff21cb1-8e90-499d-b5a0-6839fb83e70f,Still_avaliable,x4-2227164k,g,15.00
1842,1849,Goodmans Qi Wireless Charging Phone Stand,Â£15.00,134g,diy,9769724533935,2012-05-20,a7910f74-c2b6-4144-98b7-30ca68f34d2d,Still_avaliable,i3-8338545Z,g,15.00
1843,1850,RAC 12V Wet & Dry Vacuum,Â£18.00,820g,diy,3113855860327,1993-11-28,66d3efa0-f480-4da9-893b-e8aaff53e27b,Still_avaliable,n4-1642658b,g,18.00
1844,1851,Goodmans Qi Autosense In Car Phone Holder,Â£15.00,125g,diy,9195087467400,2016-09-20,efb472f1-8f00-448e-a874-9fa9812eeab5,Still_avaliable,A3-7619070S,g,15.00
1845,1852,Beldray Telescopic Ladder 2.9m,Â£69.00,9.4kg,diy,8518402353072,2006-10-07,cfe701da-6493-4a7f-83cf-9aab1650f689,Still_avaliable,i6-2851854w,kg,69.00

In [146]:
# Convert the numbers column to string
df['weight'] = df['weight'].astype(str)

# Extract the letters from the numbers column
df['unit'] = df['weight'].str.extract(r'([a-zA-Z]+)')

# Print the resulting DataFrame with the extracted letters
df['unit'].unique()

array(['kg', 'g', 'nan', 'x', 'GO', 'Z', 'MX', 'ml', 'oz'], dtype=object)

In [126]:
filtered = df[df['unit'] == 'x']
filtered

,product_name,product_price,weight,category,EAN,date_added,uuid,removed,product_code,unit,numbers,weight (KG)
298,Pedigree Vital Protection Dog Food in Jelly 12...,Â£4.49,12 x 100g,pets,2439834307647,1995-06-25,5ec5a431-7330-4d9e-bf3c-702fc85f6efe,Still_avaliable,d4-9698287C,x,12.0,1.200
299,Cesar Country Kitchen Dog Food 8 x 150g,Â£5.49,8 x 150g,pets,5158002633117,1994-03-22,c379d810-61bf-4ed2-994c-0d3308d5be7b,Still_avaliable,M4-1688574Q,x,8.0,1.200
300,Pedigree Puppy Dog Food in Jelly 12pk,Â£4.49,12 x 100g,pets,5242405808651,2014-05-20,40963728-bdae-48f1-beec-7c6dd0225921,Still_avaliable,J4-5517838n,x,12.0,1.200
301,Pedigree Dog Food in Gravy 12pk,Â£4.49,12 x 100g,pets,6160542808008,2020-12-20,3109d9e8-56b5-4233-a682-0bcdb38182b0,Still_avaliable,v6-1209149g,x,12.0,1.200
302,Pedigree Dog Food in Jelly 12pk,Â£4.49,12 x 100g,pets,3928398867180,2006-03-27,28625483-3723-4eaa-9f14-a1a16affbed8,Still_avaliable,C5-0179057G,x,12.0,1.200
303,Chappie Dog Food 6 x 412g,Â£5.99,6 x 412g,pets,8155594260063,1993-06-30,6b86f83c-fccf-42eb-b1d5-3971915c18a5,Still_avaliable,Z4-535642u,x,6.0,2.472
304,Butcher's Puppy Meaty Chunks in Jelly Tins 6 x...,Â£4.35,6 x 400g,pets,9386802556862,2019-06-16,a21e8202-de56-40bf-aee9-1b65989b1030,Still_avaliable,x0-3876046p,x,6.0,2.400
305,Pedigree Vital Protection Dog Food in Jelly 12...,Â£4.49,12 x 100g,pets,6045981116269,1996-10-12,39ce65ab-d873-4953-a363-af9a705ca1ef,Still_avaliable,O3-6314460b,x,12.0,1.200
381,Sheba Classics Ocean Selection in Terrine 8 x 85g,Â£3.49,8 x 85g,pets,5864355297349,2014-01-01,96f4d10f-1cb0-4898-b170-8dcd54c78f05,Still_avaliable,I3-7208040s,x,8.0,0.680
382,Classic Jumbo Pack Cat Food in Jelly 40 x 100g,Â£10.99,40 x 100g,pets,3610175997493,2003-09-03,003e2c32-2d88-4ace-9d3c-97863fb62959,Still_avaliable,Y9-9993954b,x,40.0,4.000
383,Sheba Classics Ocean Selection in Terrine 12 x...,Â£4.29,12 x 85g,pets,7913138139807,2006-12-10,e35ab52e-f5db-4e96-b8c0-a9393a5e33a8,Still_avaliable,s3-7992277H,x,12.0,1.020
384,Sheba Classics Ocean Selection in Terrine 8 x 85g,Â£3.49,8 x 85g,pets,8297142436817,2015-04-29,9df3a039-6cbd-4160-aa45-5f482b236c69,Still_avaliable,m4-507493i,x,8.0,0.680
385,Classic Jumbo Pack Cat Food in Jelly 40 x 100g,Â£10.99,40 x 100g,pets,4130594949815,2011-12-08,99cf7bf2-a611-4273-8aac-f426db6c863c,Still_avaliable,H5-5776855X,x,40.0,4.000
386,Sheba Classics Ocean Selection in Terrine 12 x...,Â£4.29,12 x 85g,pets,7407445491692,1993-04-22,e4b978ae-fe4d-4118-a9f8-f8cbd8ff1c71,Still_avaliable,i3-7714502N,x,12.0,1.020
1562,Just Balmy 2D Wall's Lip Balm Set,Â£4.00,3 x 2g,health-and-beauty,1151910730323,2006-07-30,6330007c-a70b-41b3-a048-fb38c258d169,Still_avaliable,R9-8669060I,x,3.0,0.006
1563,Just Balmy 2D Barratt Sweet Treats Lip Balm Set,Â£4.00,3 x 2g,health-and-beauty,9828103898017,1997-03-11,68e38307-42c5-4e3f-a27f-f32d05f9a637,Still_avaliable,Z7-8693140R,x,3.0,0.006
1571,Palmolive Natural Soap - Moisture Care 3 x 90g,Â£1.00,3 x 90g,health-and-beauty,1692944856882,1997-02-19,d109ec4d-6f3e-4520-b78a-b34a32fd8f1e,Still_avaliable,c8-1525632E,x,3.0,0.270
1668,Nescafe Dolce Gusto - Latte Machiato 16pk,Â£3.69,16 x 10g,food-and-drink,8586844844403,2014-06-05,e3523dd6-8c02-46c4-848f-d7415776acb2,Still_avaliable,P4-7471291z,x,16.0,0.160
1669,Nescafe Dolce Gusto - Flat White 16pk,Â£3.69,16 x 10g,food-and-drink,5015230815305,1992-12-29,ba73ad16-8998-4799-859d-88691a9c2d54,Still_avaliable,u3-6199715i,x,16.0,0.160
1676,Nescafe Dolce Gusto - Latte Machiato 16pk,Â£3.69,16 x 10g,food-and-drink,8057338051145,2005-08-23,07aa6951-d029-46ed-8a63-12e3ba9db4b7,Removed,C4-9106468S,x,16.0,0.160
1677,Nescafe Dolce Gusto - Flat White 16pk,Â£3.69,16 x 10g,food-and-drink,8490641014047,1997-11-09,554505a2-a18d-4d39-bebf-d81ccbff148f,Still_avaliable,C2-4933266o,x,16.0,0.160
1689,John West Pink Salmon in Brine 3 x 132g,Â£3.99,3 x 132g,food-and-drink,9395762803091,2022-08-16,3d8e0941-109f-4c3e-bc16-3de9d200c132,Still_avaliable,W4-1094978l,x,3.0,0.396
1690,Ocean Fresh Tuna Chunks in Oil 5 x 145g,Â£3.39,5 x 145g,food-and-drink,3487686391726,1995-02-06,883ff3f7-f6f4-427a-8c10-fe37e0bbf1ed,Still_avaliable,z3-5944487U,x,5.0,0.725
1692,Heinz Tomato Soup 4 x 400g,Â£3.39,4 x 400g,food-and-drink,1685057010180,2020-10-10,d4d54e79-cd6d-4f4b-9bee-4058403299de,Removed,G8-4206489Y,x,4.0,1.600
1700,John West Pink Salmon in Brine 3 x 132g,Â£3.99,3 x 132g,food-and-drink,4758183010205,2006-07-19,6f5b78f6-02cd-4ef1-ba53-678109bf9294,Still_avaliable,L5-106382J,x,3.0,0.396
1701,Ocean Fresh Tuna Chunks in Oil 5 x 145g,Â£3.39,5 x 145g,food-and-drink,9444749850532,2001-05-04,d64a8810-431f-422d-a0b7-87265bfa702e,Still_avaliable,O2-1543849C,x,5.0,0.725
1727,Mrs Tilly's Festive Brandy Fudge 400g,Â£3.99,2 x 200g,food-and-drink,2548181647709,2002-03-02,9d1dae52-2e77-4299-ac68-68e8e6c8b3e0,Still_avaliable,K8-1086936D,x,2.0,0.400
1752,Mrs Tilly's Festive Brandy Fudge 400g,Â£3.99,2 x 200g,food-and-drink,4880675517869,2022-08-18,d88eedf9-3394-4382-a3d1-85767e5e4ff0,Still_avaliable,M5-8164943v,x,2.0,0.400

In [123]:

def extract_numeric_value(weight):
    # we can remove last value 'g'
    values = weight[:-1]
    # Split the string by 'x' and extract the first part and multiply by second part
    parts = values.split('x')
    first_value = int(parts[0])
    other_value = int(parts[1])
    return (first_value * other_value) /1000

In [19]:
string = df['weight']
new_string = string[:-1]

In [20]:
df["numbers"] = df["weight"].str.extract("(\d*\.?\d+)", expand=True)
df['numbers'] = df['numbers'].astype(float)
df

,product_name,product_price,weight,category,EAN,date_added,uuid,removed,product_code,unit,weight_without_g,numbers
0,FurReal Dazzlin' Dimples My Playful Dolphin,Â£39.99,1.6kg,toys-and-games,7425710935115,2005-12-02,83dc0a69-f96f-4c34-bcb7-928acae19a94,Still_avaliable,R7-3126933h,kg,1.6k,1.60
1,Tiffany's World Day Out At The Park,Â£12.99,0.48kg,toys-and-games,487128731892,2006-01-09,712254d7-aea7-4310-aff8-8bcdd0aec7ff,Still_avaliable,C2-7287916l,kg,0.48k,0.48
2,Tiffany's World Pups Picnic Playset,Â£7.00,590g,toys-and-games,1945816904649,1997-03-29,b089ef6f-b628-4e37-811d-fffe0102ba64,Still_avaliable,S7-1175877v,g,590,590.00
3,Tiffany's World Wildlife Park Adventures,Â£12.99,540g,toys-and-games,1569790890899,2013-03-20,d55de422-8b98-47d6-9991-e4bc4c5c0cb0,Removed,D8-8421505n,g,540,540.00
4,Cosatto Cosy Dolls Pram,Â£30.00,1.91kg,toys-and-games,7142740213920,2007-12-23,7945b657-cb02-4cc5-96cf-f65ed0a8f235,Still_avaliable,B6-2596063a,kg,1.91k,1.91
...,...,...,...,...,...,...,...,...,...,...,...,...
1848,Goodmans Qi Autosense In Car Phone Holder,Â£15.00,125g,diy,8185827751600,2020-08-28,3ff21cb1-8e90-499d-b5a0-6839fb83e70f,Still_avaliable,x4-2227164k,g,125,125.00
1849,Goodmans Qi Wireless Charging Phone Stand,Â£15.00,134g,diy,9769724533935,2012-05-20,a7910f74-c2b6-4144-98b7-30ca68f34d2d,Still_avaliable,i3-8338545Z,g,134,134.00
1850,RAC 12V Wet & Dry Vacuum,Â£18.00,820g,diy,3113855860327,1993-11-28,66d3efa0-f480-4da9-893b-e8aaff53e27b,Still_avaliable,n4-1642658b,g,820,820.00
1851,Goodmans Qi Autosense In Car Phone Holder,Â£15.00,125g,diy,9195087467400,2016-09-20,efb472f1-8f00-448e-a874-9fa9812eeab5,Still_avaliable,A3-7619070S,g,125,125.00
1852,Beldray Telescopic Ladder 2.9m,Â£69.00,9.4kg,diy,8518402353072,2006-10-07,cfe701da-6493-4a7f-83cf-9aab1650f689,Still_avaliable,i6-2851854w,kg,9.4k,9.40

In [121]:
df['unit'] = df['unit'].astype(str)
df.dtypes

product_name      object
product_price     object
weight            object
category          object
EAN               object
date_added        object
uuid              object
removed           object
product_code      object
unit              object
numbers          float64
new              float64
weight (KG)      float64
dtype: object

In [119]:
# df['new'] = df.loc[df['unit'] == 'g', df['numbers']/ 1000
# df['new'] = df.loc[df['unit'] == 'kg', df['numbers']
df['weight (KG)'] = df.loc[df['unit'] == 'x', 'weight'].apply(lambda x: extract_numeric_value(x))
df['weight (KG)'] = df['new'].mask(df['unit'] == 'ml', df['numbers']/ 1000)
df['weight (KG)'] = df['new'].mask(df['unit'] == 'kg', df['numbers'])
df['weight (KG)'] = df['new'].mask(df['unit'] == 'g', df['numbers']/ 1000)
df['weight (KG)'] = df['new'].mask(df['unit'] == 'oz', df['numbers']/ 35.27)



df

,product_name,product_price,weight,category,EAN,date_added,uuid,removed,product_code,unit,numbers,new,weight (KG)
0,FurReal Dazzlin' Dimples My Playful Dolphin,Â£39.99,1.6kg,toys-and-games,7425710935115,2005-12-02,83dc0a69-f96f-4c34-bcb7-928acae19a94,Still_avaliable,R7-3126933h,kg,1.60,1.600,1.600
1,Tiffany's World Day Out At The Park,Â£12.99,0.48kg,toys-and-games,487128731892,2006-01-09,712254d7-aea7-4310-aff8-8bcdd0aec7ff,Still_avaliable,C2-7287916l,kg,0.48,0.480,0.480
2,Tiffany's World Pups Picnic Playset,Â£7.00,590g,toys-and-games,1945816904649,1997-03-29,b089ef6f-b628-4e37-811d-fffe0102ba64,Still_avaliable,S7-1175877v,g,590.00,0.590,0.590
3,Tiffany's World Wildlife Park Adventures,Â£12.99,540g,toys-and-games,1569790890899,2013-03-20,d55de422-8b98-47d6-9991-e4bc4c5c0cb0,Removed,D8-8421505n,g,540.00,0.540,0.540
4,Cosatto Cosy Dolls Pram,Â£30.00,1.91kg,toys-and-games,7142740213920,2007-12-23,7945b657-cb02-4cc5-96cf-f65ed0a8f235,Still_avaliable,B6-2596063a,kg,1.91,1.910,1.910
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1848,Goodmans Qi Autosense In Car Phone Holder,Â£15.00,125g,diy,8185827751600,2020-08-28,3ff21cb1-8e90-499d-b5a0-6839fb83e70f,Still_avaliable,x4-2227164k,g,125.00,0.125,0.125
1849,Goodmans Qi Wireless Charging Phone Stand,Â£15.00,134g,diy,9769724533935,2012-05-20,a7910f74-c2b6-4144-98b7-30ca68f34d2d,Still_avaliable,i3-8338545Z,g,134.00,0.134,0.134
1850,RAC 12V Wet & Dry Vacuum,Â£18.00,820g,diy,3113855860327,1993-11-28,66d3efa0-f480-4da9-893b-e8aaff53e27b,Still_avaliable,n4-1642658b,g,820.00,0.820,0.820
1851,Goodmans Qi Autosense In Car Phone Holder,Â£15.00,125g,diy,9195087467400,2016-09-20,efb472f1-8f00-448e-a874-9fa9812eeab5,Still_avaliable,A3-7619070S,g,125.00,0.125,0.125
1852,Beldray Telescopic Ladder 2.9m,Â£69.00,9.4kg,diy,8518402353072,2006-10-07,cfe701da-6493-4a7f-83cf-9aab1650f689,Still_avaliable,i6-2851854w,kg,9.40,9.400,9.400

In [164]:
df.isna().sum()

date_uuid           0
user_uuid           0
card_number         0
store_code          0
product_code        0
product_quantity    0
dtype: int64

In [25]:
df = df.dropna(subset=['product_name'],how='any')

In [147]:
df = df[df['unit'] != 'GO']
df = df[df['unit'] != 'MX']
df = df[df['unit'] != 'Z']

In [150]:
df['category'].unique()

array(['toys-and-games', 'sports-and-leisure', 'pets', 'homeware',
       'health-and-beauty', 'food-and-drink', 'diy'], dtype=object)